-- MySQL Script generated by MySQL Workbench
-- Mon Dec 23 15:59:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `dim_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_customers` (
  `CustomerID` INT(11) NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(50) NOT NULL,
  `ContactName` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `City` VARCHAR(20) NOT NULL,
  `PostalCode` VARCHAR(10) NOT NULL,
  `Country` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_shippers` (
  `ShipperID` INT NOT NULL AUTO_INCREMENT,
  `ShipperName` VARCHAR(25) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ShipperID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_employees` (
  `EmployeeID` INT(11) NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(15) NOT NULL,
  `FirstName` VARCHAR(15) NOT NULL,
  `BirthDate` DATETIME NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_products` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(50) NOT NULL,
  `Unit` VARCHAR(25) NOT NULL,
  `Price` DECIMAL(10,0) NOT NULL,
  `CategoryName` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_suppliers` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `SupplierName` VARCHAR(50) NOT NULL,
  `ContactName` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `City` VARCHAR(20) NOT NULL,
  `PostalCode` VARCHAR(10) NOT NULL,
  `Country` VARCHAR(15) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_order_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_order_date` (
  `OrderDateID` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATE NOT NULL,
  `day` INT NOT NULL,
  `dayOfWeek` INT NOT NULL,
  `dayOfWeekAsString` VARCHAR(45) NOT NULL,
  `week` INT NOT NULL,
  `month` INT NOT NULL,
  `monthAsString` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `quarter` INT NOT NULL,
  PRIMARY KEY (`OrderDateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dim_order_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dim_order_time` (
  `OrderTimeID` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIME NOT NULL,
  `hour` INT NOT NULL,
  `ampm` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`OrderTimeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fact_orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fact_orderdetails` (
  `OrderDetailID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderDate` DATETIME NOT NULL,
  `Quantity` INT(11) NOT NULL,
  `TotalPrice` DECIMAL(10,0) NOT NULL,
  `CustomerID` INT(11) NOT NULL,
  `ShipperID` INT NOT NULL,
  `EmployeeID` INT(11) NOT NULL,
  `ProductID` INT NOT NULL,
  `SupplierID` INT NOT NULL,
  `OrderDateID` INT NOT NULL,
  `OrderTimeID` INT NOT NULL,
  PRIMARY KEY (`OrderDetailID`),
  INDEX `fk_fact_orders_dim_customers1_idx` (`CustomerID` ASC),
  INDEX `fk_fact_orders_dim_shippers1_idx` (`ShipperID` ASC),
  INDEX `fk_fact_orders_dim_employees1_idx` (`EmployeeID` ASC),
  INDEX `fk_fact_orders_dim_products1_idx` (`ProductID` ASC),
  INDEX `fk_fact_orders_dim_suppliers1_idx` (`SupplierID` ASC),
  INDEX `fk_fact_orders_dim_order_date1_idx` (`OrderDateID` ASC),
  INDEX `fk_fact_orders_dim_review_time1_idx` (`OrderTimeID` ASC),
  CONSTRAINT `fk_fact_orders_dim_customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `dim_customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_shippers1`
    FOREIGN KEY (`ShipperID`)
    REFERENCES `dim_shippers` (`ShipperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `dim_employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `dim_products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_suppliers1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `dim_suppliers` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_order_date1`
    FOREIGN KEY (`OrderDateID`)
    REFERENCES `dim_order_date` (`OrderDateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_orders_dim_review_time1`
    FOREIGN KEY (`OrderTimeID`)
    REFERENCES `dim_order_time` (`OrderTimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
